theme = "chunky_dates_fr"
ignoreFiles = [ "decembre2020" ]

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"



[languages]
    [languages.en]
        title = "Coderacy"
        description = "Computer literacy is not enough. We need Code literacy."
        #homepageImage = "/images/logo_a_la_main.png"
        baseURL = "http://en.coderatie.org/"
        contentDir = "content/en"
        languageName = "English"
        languageCode = "en-us"
        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "stakes"
                name = "At stake"
                url = "/stakes"
                weight=5
            [[languages.en.menu.main]]
                identifier = "vision"
                name = "Vision"
                url = "/vision"
                weight=10
            [[languages.en.menu.main]]
                identifier = "research-project"
                name = "Research project"
                url = "/research-project"
                weight=15
            [[languages.en.menu.main]]
                identifier = "how-to-help"
                name = "How can I help?"
                url = "/how-to-help"
                weight=20
            #[[languages.en.menu.main]]
                #identifier = "toc"
                #name = "Table of content"
                #url = "/toc"
    [languages.fr]
        title = "Codératie"
        description = "Au delà de la littératie numérique, il faut promouvoir une littératie du Code."
        #homepageImage = "/images/logo_a_la_main.png"
        baseURL = "http://coderatie.org/"
        contentDir = "content/fr"
        languageName = "Français"
        languageCode = "fr-ca"
        [languages.fr.menu]
            [[languages.fr.menu.main]]
                identifier = "stakes"
                name = "Enjeux"
                url = "/les-enjeux"
                weight=5
            [[languages.fr.menu.main]]
                identifier = "vision"
                name = "Vision"
                url = "/vision"
                weight=10
            [[languages.fr.menu.main]]
                identifier = "research-project"
                name = "Projet de recherche"
                url = "/projet-de-recherche"
                weight=15
            [[languages.fr.menu.main]]
                identifier = "how-to-help"
                name = "Comment puis-je aider?"
                url = "/comment-aider"
                weight=20
            #[[languages.fr.menu.main]]
                #identifier = "toc"
                #name = "Table des matères"
                #url = "/index"

[params]
    showLanguageSwitcher = true

    [params.social]
        rss = true
        email = "mathieu.bergeron@cmontmorency.qc.ca"
        github = "https://github.com/mathieu-bergeron/coderatie"
